name: NPM Scan Secure Bank
on: [pull_request]
jobs:
NPM-Scan:
  runs-on: ubuntu-latest
    steps:
      - https://github.com/actions/checkout
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm scan

      